# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 06:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0002_auto_20170320_0408'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Information',
        ),
        migrations.RemoveField(
            model_name='message',
            name='chat_room',
        ),
        migrations.RemoveField(
            model_name='message',
            name='chat_user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='dest_message',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
